apiVersion: v1
kind: Service
metadata:
  name: springboot
  namespace: default
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: springboot
    origin: binblee
---
apiVersion: v1
kind: Service
metadata:
  name: springboot-preview-service
  namespace: default
  annotations:
    argocd.argoproj.io/compare-options: IgnoreExtraneous
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: springboot
    origin: binblee
